### ISSUE TITLE
Failed to lookup Group

### ISSUE THREAD

**Issue by Greg-Boggs** [bbatsche/Ansible-PHP-Site-Role#2]
I tried using this role today (without your Base role) and I got this error:

`
TASK [bbatsche.Nginx : Propogate Web Admin Group in Sites-Available] ***********
fatal: [128.199.246.116]: FAILED! => {"changed": false, "failed": true, "gid": 0, "group": "root", "mode": "0755", "msg": "chgrp failed: failed to look up group web-admin", "owner": "root", "path": "/etc/nginx/sites-available", "size": 4096, "state": "directory", "uid": 0}
`

**Comment by bbatsche** [comment]
Please see issue #1.
